import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Certificate from '../components/Certificate';
import Spinner from '../components/Spinner';

export default function Home() {
  const [Url, setUrl] = useState('');
  const [Cert, setCert] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `http://localhost:8000/api/cert/getSSLCert`;

  const fetchCert = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.post(url,{Url}).then((response) => {
      setCert(response.data);
       console.log(response.data);
    });
    // setUrl('');
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>SSL - Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {/* Overlay */}
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
        {/* Background image */}
        <Image
          src='https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
          layout='fill'
          className='object-cover'
        />

        {/* Search */}
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          <form
            onSubmit={fetchCert}
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
          >
            <div>
              <input
                onChange={(e) => setUrl(e.target.value)}
                className='bg-transparent border-none text-white focus:outline-none text-2xl'
                type='text'
                placeholder='Search domain'
              />
            </div>
            <button onClick={fetchCert}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>

        {/* Certificate */}
        {Cert.issuer && <Certificate data={Cert} />}
      </div>
    );
  }
}
